### ISSUE TITLE
과제명, 강의명이 수정되지 않음

### ISSUE THREAD

**Issue by gmldms784** [CSUOS/nera#109]

**Comment by powergee** [comment]
@gmldms784  앗 혹시 이문제는 제가 forceUpdate를 제거해서 그런 것일까요..?

**Comment by Thereisnotruth** [comment]
백엔드 문제였습니다. 과제 변경 api에 학생목록, 과제 정보, 발행시간, 마감기한, 문제목록까지만 수정되도록 해놓고 과제명은 빼먹었네요;;
