### ISSUE TITLE
답안 작성시 자동저장기능

### ISSUE THREAD

**Issue by iwanhae** [CSUOS/nera#43]
답안을 작성할때 아래 그림과 같이 오른쪽 위에 버튼을 꼭 눌러줘야하는데
![image](https://user-images.githubusercontent.com/14325010/92255051-c01d1980-ef0c-11ea-93ff-2d1cb77e9ad8.png)
잘 보이지도 않고 까먹기가 쉽습니다.

1. 페이지를 나가려고할때 페이지를 나갈껀지 물어보는 팝업창과
2. 답안 작성시 주기적으로 자동으로 서버에 저장되는 기능 (수정내용 발생시 10초에 한번 자동저장기능이 있으면 좋지않을까요?) 이 있으면 좋을 것 같습니다.

**Comment by powergee** [comment]
마침 이번 PR #38 에서 자동 저장과 경고 기능을 포함하여 구현할 예정이였는데, 이슈 발행해주셔서 감사합니다!
