### ISSUE TITLE
문제가 여러개 있을때 학생입장에서 저장이 제대로 안됨

### ISSUE THREAD

**Issue by iwanhae** [CSUOS/nera#62]
1번문제 작성하고 저장을 안한상태로

2번문제를 수정하고 저장하면 2번문제는 저장이 되는데 1번문제는 저장이 안됨

**Comment by powergee** [comment]
@iwanhae 
1번 문제를 작성하고 아직 자동저장이 되지 않은 상태에서, 빠르게 2번 문제를 작성하면 1번 문제가 저장되지 않는다는 말씀이신가요?

**Comment by iwanhae** [comment]
네, 현재 그런 이슈가 확인되네요. 제가 테스트용으로 올려놓은 문제 3개짜리 과제에서 확인해보세요.

**Comment by powergee** [comment]
제가 따로 과제를 만들어서 실제 과제를 작성할 때 처럼 5분간 2번부터 1번까지 작성해보았는데 늦게 작성한 1번은 저장되고 2번은 저장되지 않는 것으로 확인했습니다. 과제를 작성하는 속도는 버그와 무관한 것으로 보입니다.

굉장히 위험한 버그인 것으로 생각되어, 책임지고 해결하도록 하겠습니다!
