### ISSUE TITLE
수강생 목록에서 번호를 입력하지 않으면 null이 저장되는 현상

### ISSUE THREAD

**Issue by powergee** [CSUOS/nera#63]
![스크린샷, 2020-09-07 00-31-58](https://user-images.githubusercontent.com/49356944/92329455-7e25dc00-f0a2-11ea-85a7-8731c8b70edb.png)
![스크린샷, 2020-09-07 00-32-35](https://user-images.githubusercontent.com/49356944/92329457-7f570900-f0a2-11ea-890e-185ca0ada3c8.png)

수강생 목록에서 학생을 추가해놓고 실제 번호를 적지 않으면 수강생 목록에 null이 저장되는 현상을 확인했습니다.

**Comment by gmldms784** [comment]
아 이거 과제 제출 시에 문제네요...! 수강생 목록에서는 전처리 다 해줬는데, 여기서는 아직 코드가 부족하네요. 똑같이 전처리과정 추가해두겠습니다.
