### ISSUE TITLE
assignmentState가 시간에 따라 수정되지 않고 초기값으로 유지되는 현상

### ISSUE THREAD

**Issue by powergee** [CSUOS/nera#70]
시간에 따라 assignmentState가 변하지 않는 버그를 발견하였습니다. 과제의 마감 기한을 지나거나, 과제의 마감 기한을 연장하여 assignmentState가 변하여야 하는 상황에도 백엔드에서 전달받은 assignmentState가 변하지 않고 초기에 설정한 값으로 유지됩니다. 아래는 이를 재현하는 과정입니다.

1. 발행시간은 지났지만 이미 마감기한이 지난 과제를 생성합니다. (ex. 현재 시간이 10시라면 발행시간을 8시, 마감기한을 9시로 설정)
2. 이렇게 되면 assignmentState가 2입니다. (정상)
3. 다시 과제 설정 페이지로 돌아가서 과제의 마감기한을 현재 시간보다 미래로 설정합니다.
4. 이 때 과제의 assignmentState가 변해야 하지만 초기값 그대로 2가 유지됩니다. (버그)

![1  지난 과제 생성](https://user-images.githubusercontent.com/49356944/92593203-ad735d80-f2db-11ea-9c26-3df018e48bd7.png)
![2  처음에 마감된 상태 (정상)](https://user-images.githubusercontent.com/49356944/92593206-af3d2100-f2db-11ea-8dae-df1dc19fc7a3.png)
![3  마감 시간 수정](https://user-images.githubusercontent.com/49356944/92593208-afd5b780-f2db-11ea-858e-d2f3ea9e46a3.png)
![4  assignmentState가 수정되지 않았음 (버그)](https://user-images.githubusercontent.com/49356944/92593211-b06e4e00-f2db-11ea-908b-6c1d963c128a.png)

**Comment by Thereisnotruth** [comment]
과제의 상태를 계산하는 calState 함수에서 현재 시간을 ISO 표준시간이 아닌 현재 한국시간으로 설정하여 생긴 문제인 것 같습니다.
DB에 저장할 때에는 별도의 수정 없이 프론트에서 넘어온 시간 정보를 그대로 저장하도록 하고 상태를 계산할 때 9시간이 더해진 한국의 현재 시간에서 ISO 표준시간을 뺐기 때문에 본래 의도한 대로라면 음수여야 할 값이 양수가 나왔기 때문에 이러한 문제가 발생한 것으로 보입니다. 바로 수정하여 PR 넣도록 하겠습니다.
