### ISSUE TITLE
환경변수로 작동

### ISSUE THREAD

**Issue by iwanhae** [CSUOS/nera#8]
DB주소, rabums 주소와 같은 공개되어도 상관은 없지만, 바뀔 가능성이 높은 정보는 Config.ts 파일에서 관리하게 할것.

Config.ts 는 기본값 설정 후 환경변수를 불러와서 해당 값을 대치하는식으로 작동하게 할 것.

**Comment by Thereisnotruth** [comment]
config.ts로 vault에서 환경변수를 가져오도록 구현하였음.
