### ISSUE TITLE
과제 작성 페이지 UI/UX 개선

### ISSUE THREAD

**Issue by powergee** [CSUOS/nera#88]
1. 과제 저장 상태를 나타내는 컴포넌트를 상단에 고정 (#45 의 내용과 같음)
2. ```[]```로 링크를 만들고 ```()```로 주소를 부여하지 않았다면 빈 링크를 만들 수 없다는 경고 삽입
3. 저장 지연 시간을 5초에서 1초로 조정
4. 채점이 완료되었을 때 점수를 확인하는 페이지에서 MarkdownEditor 대신 MarkdownViewer 사용
5. Ctrl+S로 수동 저장 지원 및 Snackbar로 안내문 표시
6. 홈 화면으로 다시 돌아가는 버튼 추가
7. 마크다운에 대한 안내문 추가
8. 과제 상태가 '진행 중'일 때만 답안을 저장하도록 수정 및 확인
9. MarkdownEditor에서 HTML 태그 사용 차단

**Comment by gmldms784** [comment]
홈화면으로 다시 돌아가는 버튼은 무엇인가요?
