### ISSUE TITLE
새로고침 시 사이드바의 로고가 없어지는 현상

### ISSUE THREAD

**Issue by gmldms784** [CSUOS/nera#89]

**Comment by Thereisnotruth** [comment]
SideBar.js의 이미지 경로를 ./img/logo1.png에서 ../img/logo1.png로 바꾸니 해결되긴 하는데 이게 왜 되는 건지 모르겠습니다..

**Comment by gmldms784** [comment]
오... 해결됐으면 됐죠 :> ㅋㅋㅋㅋ 루트가 public 폴더로 되어있을텐데 왜인지는 저도 모르겠네요 ㅠㅠ 일단 PR 넣어주세요! 감사합니다
