### ISSUE TITLE
쿠키가 만료되었을 때 로그인으로 리다이렉션되지 못하고 교착상태에 빠지는 현상

### ISSUE THREAD

**Issue by powergee** [CSUOS/nera#93]
프론트에서 getUserInfo에서 쿠키가 만료되어도 이를 감지 않아 문제가 생기고,
백엔드에서는 쿠키가 만료된 상태에서 과제를 조회했을 때 401이 아닌 404를 반환한다.

**Comment by Thereisnotruth** [comment]
404를 반환하는 오류는 쿠키가 만료되었을  때의 에러핸들링이 빠져있어서 그런 것으로 보입니다. auth.ts에서 catch 블록에 ctx.throw(401, '인증 실패');를 추가해주시면 해결됩니다.

**Comment by powergee** [comment]
> 404를 반환하는 오류는 쿠키가 만료되었을 때의 에러핸들링이 빠져있어서 그런 것으로 보입니다. auth.ts에서 catch 블록에 ctx.throw(401, '인증 실패');를 추가해주시면 해결됩니다.

@Thereisnotruth  감사합니다, 그렇게 수정해서 나중에 PR하도록 하겠습니다!
