### ISSUE TITLE
학생이 /v1/assignment를 통해 답안을 저장하면 score가 덮어써지는 현상

### ISSUE THREAD

**Issue by powergee** [CSUOS/nera#94]
기존의 assignment.ts의 코드에서는 학생이 자신의 답안을 수정하였을 때 ```prevAnswer.answers = body.answers;```로 answers 배열 자체를 덮어써버리므로, 채점된 답안이 있었다면 이것이 덮어써짐.

![스크린샷, 2020-09-14 06-48-15](https://user-images.githubusercontent.com/49356944/93029543-8f4c8b00-f656-11ea-8077-8f7fc86be0d9.png)

**Comment by Thereisnotruth** [comment]
과제의 마감기한이 지났을 경우 요청에 에러를 내보내도록 수정하겠습니다. 감사합니다.
